[package]
name = "with-hide"
version = "0.1.0"
edition = "2021"

[dependencies]
hide-utils-core = { path = "../hide-utils-core" }

clap = { version = "4.5.7", features = ["env", "wrap_help", "derive"] }
anyhow = "1.0.86"
log = "0.4.21"
env_logger = "0.11.3"
promptly = "0.3.1"
duct = "0.13.7"